// <auto-generated />
namespace Infra.Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class STR_TESTE : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(STR_TESTE));
        
        string IMigrationMetadata.Id
        {
            get { return "201707030215121_STR_TESTE"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return Resources.GetString("Source"); }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
